image_info:
  num_neg: 400
  num_pos: 270

  image_paths:
    positive: "positive_real"
    negative: "sun_images"
    positive_json: "labels.json"
    detect: "multiscale_test"
    video: ""

preprocessing_params:
  colors_lower: [0,0,0]
  colors_upper: [255, 255, 10]

hog_params:
  mindim: 80
  blocksize: 16
  blockstride: 8
  cellsize: 8
  nbins: 9

svm_params:
  kernel: 'linear'
  c: 1.0
  probability: True
  model_path: "hog_svm.pkl"

classifier:
  min_threshold: 0.1
